apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - envoyproxy.yaml
  - gateway-certificate.yaml
  - backend-certificate.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
  - backendtlspolicy.yaml
