apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
  labels:
    homelab.local/internal-ca-trust: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
