apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - external-secrets.yaml
  - network-edge.yaml
  - observability.yaml
  - platform.yaml
  - apps.yaml
  - sandbox.yaml
