apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  project: platform
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-crds-helm
      targetRevision: v1.8.0
      helm:
        releaseName: gateway-api-crds
        valueFiles:
          - $values/kubernetes/clusters/homelab/platform/55-gateway-api-crds/values.yaml
    - repoURL: https://github.com/yanglianglu/homelab-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
