apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/yanglianglu/homelab-platform.git
    targetRevision: main
    path: kubernetes/clusters/homelab/platform/05-kube-vip/app
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
