apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-app-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-platform
  target:
    name: argocd-github-app-repo-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
    - secretKey: url
      remoteRef:
        key: url
    - secretKey: type
      remoteRef:
        key: type
    - secretKey: githubAppID
      remoteRef:
        key: githubAppID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: githubAppInstallationID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: githubAppPrivateKey
