apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/apps.yaml
  - projects/sandbox.yaml
  - applications/platform/namespaces.yaml
  - applications/platform/policies.yaml
