apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: platform
  source:
    repoURL: https://github.com/yanglianglu/homelab-platform.git
    targetRevision: main
    path: kubernetes/clusters/homelab/platform/40-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
