apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: observability
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.78.0
      helm:
        releaseName: platform-observability
        valueFiles:
          - $values/kubernetes/clusters/homelab/observability/platform-observability/values.yaml
    - repoURL: https://github.com/yanglianglu/homelab-platform.git
      targetRevision: main
      path: kubernetes/clusters/homelab/observability/platform-observability
    - repoURL: https://github.com/yanglianglu/homelab-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
