apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: external-secrets
  namespace: observability
  labels:
    app.kubernetes.io/part-of: guest-observability
spec:
  namespaceSelector:
    matchNames:
      - external-secrets
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - external-secrets
          - external-secrets-cert-controller
          - external-secrets-webhook
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
