apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-internal-trust-bundle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "61"
spec:
  project: platform
  source:
    repoURL: https://github.com/yanglianglu/homelab-platform.git
    targetRevision: main
    path: kubernetes/clusters/homelab/platform/61-internal-trust-bundle/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
