apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
spec:
  project: data-platform
  source:
    repoURL: https://github.com/yanglianglu/homelab-platform.git
    targetRevision: main
    path: kubernetes/clusters/homelab/data-platform/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
