apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-harvester-csi
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: homelab-platform-cs-zx
        environmentSlug: prod
        secretsPath: /harvester-csi
        recursive: false
        expandSecretReferences: true
