apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harvester-csi-config
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-harvester-csi
  target:
    name: harvester-csi-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: cloud-provider-config
      remoteRef:
        key: cloud_provider_config
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
