apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harvester-slow-retain
provisioner: driver.harvesterhci.io
parameters:
  host-storage-class: slow
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
