apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-proof-harvester-default
  namespace: data-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: harvester
  resources:
    requests:
      storage: 1Gi
