apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "59"
spec:
  project: platform
  sources:
    - repoURL: quay.io/jetstack/charts
      chart: trust-manager
      targetRevision: v0.22.1
      helm:
        releaseName: trust-manager
        valueFiles:
          - $values/kubernetes/clusters/homelab/platform/59-trust-manager/values.yaml
    - repoURL: https://github.com/yanglianglu/homelab-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
