crds:
  enabled: true
  keep: true

app:
  trust:
    namespace: cert-manager

nodeSelector:
  homelab.local/node-class: general

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    memory: 256Mi

defaultPackage:
  enabled: false
