apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects
  - platform/00-namespaces/application.yaml
  - platform/05-kube-vip/application.yaml
  - platform/10-external-secrets/application.yaml
  - platform/15-metrics-server/application.yaml
  - platform/16-kubelet-csr-approver/application.yaml
  - platform/20-infisical/application.yaml
  - platform/30-argocd-repo-access/application.yaml
  - platform/40-policies/application.yaml
  - platform/50-harvester-csi/application.yaml
  - platform/55-gateway-api-crds/application.yaml
  - platform/56-envoy-gateway/application.yaml
  - platform/57-cert-manager/application.yaml
  - platform/58-internal-pki/application.yaml
  - platform/59-trust-manager/application.yaml
  - platform/61-internal-trust-bundle/application.yaml
  - observability/platform-observability/application.yaml
  - data-platform/application.yaml
  - apps/whoami-tls/application.yaml
  - apps/whoami/application.yaml
