apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects
  - platform/00-namespaces/application.yaml
  - platform/05-kube-vip/application.yaml
  - platform/10-external-secrets/application.yaml
  - platform/20-infisical/application.yaml
  - platform/30-argocd-repo-access/application.yaml
  - platform/40-policies/application.yaml
  - data-platform/application.yaml
  - apps/whoami/application.yaml
