crds:
  enabled: true
  keep: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

global:
  nodeSelector:
    homelab.local/node-class: general

resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    memory: 384Mi

webhook:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi

cainjector:
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      memory: 384Mi

startupapicheck:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
