apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Metrics, dashboards, exporters, and alerting
  sourceRepos:
    - https://github.com/yanglianglu/homelab-platform.git
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
