apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Shared platform services for the homelab cluster
  sourceRepos:
    - https://github.com/yanglianglu/homelab-platform.git
    - https://charts.external-secrets.io
    - https://charts.harvesterhci.io
    - https://kubernetes-sigs.github.io/metrics-server/
    - docker.io/envoyproxy
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
