apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-namespaces
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/yanglianglu/homelab-platform.git
    targetRevision: main
    path: kubernetes/clusters/homelab/platform/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
